"""Fourteen D7 permutations of the exact existing compact_22 coordinates.

No point is regenerated by trigonometry. Geometry below only identifies the
public two rings; returned routes always reference original coordinate objects.
"""
import math

from simulator_client.state import Position


LENGTH_TOLERANCE_M = 1e-7
IMPROVEMENT_TOLERANCE_M = 1e-9
CONFIGS = ("bearing_mean", "early_centers")


def route_length(points):
    previous, length = Position(0., 0.), 0.
    for point in points:
        length += previous.distance_to(point)
        previous = point
    return length


def d7_candidates(points):
    """Return id0..13 metadata, where id=7*reflected+rotation_index.

    Inner index i -> (+/-i+k) mod7; outer j -> (+/-j+2k) mod14.
    Each permutation indexes the supplied original ordered route, not a new
    sorted polygon. Coordinate set identity is exact, length equality tolerant.
    """
    points = tuple(Position.coerce(p) for p in points)
    xy = [(p.x, p.y) for p in points]
    if len(points) != 22 or len(set(xy)) != 22 or xy[0] != (0., 0.):
        raise ValueError("Need the complete origin-first compact_22 point set")
    outer = 1800./math.cos(math.pi/14)+5.
    labels, lookup = [("origin", 0)], {("origin", 0): 0}
    for index, point in enumerate(points[1:], 1):
        radius = math.hypot(point.x, point.y)
        ring, count, expected_radius = (("inner", 7, 970.) if abs(radius-970.) <= LENGTH_TOLERANCE_M
                                         else ("outer", 14, outer))
        angular_index = round(math.atan2(point.y, point.x)*count/(2*math.pi)) % count
        angle = 2*math.pi*angular_index/count
        expected = expected_radius*math.cos(angle), expected_radius*math.sin(angle)
        key = ring, angular_index
        if abs(radius-expected_radius) > LENGTH_TOLERANCE_M or math.dist(xy[index], expected) > LENGTH_TOLERANCE_M or key in lookup:
            raise ValueError("Coordinates do not match the fixed public D7 rings")
        labels.append(key)
        lookup[key] = index
    if set(lookup) != {("origin", 0)} | {("inner", i) for i in range(7)} | {("outer", i) for i in range(14)}:
        raise ValueError("A complete inner/outer ring is required")
    original_length = route_length(points)
    result = []
    for reflected in (False, True):
        sign = -1 if reflected else 1
        for rotation in range(7):
            permutation = []
            for ring, i in labels:
                target = (("origin", 0) if ring == "origin" else
                          (ring, (sign*i+rotation) % 7) if ring == "inner" else
                          (ring, (sign*i+2*rotation) % 14))
                permutation.append(lookup[target])
            route = tuple(points[i] for i in permutation)
            length = route_length(route)
            if sorted(permutation) != list(range(22)) or permutation[0] != 0 or abs(length-original_length) > LENGTH_TOLERANCE_M:
                raise ValueError("D7 route failed identity or length verification")
            result.append(dict(id=len(result), rotation_index=rotation, reflected=reflected,
                permutation=permutation, route_length_m=length))
    if result[0]["permutation"] != list(range(22)) or len({tuple(x["permutation"]) for x in result}) != 14:
        raise ValueError("Invalid D7 identity or duplicate route")
    return result


def select_feedback_symmetry(points, candidates, *, config, bearings, centers, known_count):
    """Finite deterministic proxy only; no source position/type inference.

    bearings: one observed bearing per directional-feedback channel.
    centers: observed canonical-region MEC centers in channel order.
    The geometry remains a certificate independently of the selected proxy.
    """
    if config not in CONFIGS:
        raise ValueError("Unknown feedback-symmetry configuration")
    if type(known_count) is not int or not 0 <= known_count <= 20:
        raise ValueError("Invalid observed source count")
    points = tuple(Position.coerce(p) for p in points)
    bearings = tuple(float(a) for a in bearings)
    centers = tuple(Position.coerce(p) for p in centers)
    if any(not math.isfinite(a) for a in bearings):
        raise ValueError("Bearings must be finite")
    sine = math.fsum(math.sin(math.radians(a)) for a in bearings)
    cosine = math.fsum(math.cos(math.radians(a)) for a in bearings)
    norm = math.hypot(sine, cosine)
    concentration = norm/len(bearings) if bearings else 0.
    mean = math.degrees(math.atan2(sine, cosine)) % 360 if norm > 1e-15 else None
    scored = []
    for candidate in candidates:
        route = tuple(points[i] for i in candidate["permutation"])
        if config == "bearing_mean":
            angle = math.degrees(math.atan2(route[1].y, route[1].x)) % 360
            score = abs((angle-mean+180) % 360-180) if mean is not None else None
        else:
            score = math.fsum(min(center.distance_to(p) for p in route[1:4]) for center in centers)
        scored.append(dict(candidate, score=score))
    selected, status = 0, "identity_best"
    if known_count >= 16:
        status = "source_count_cap"
    elif config == "bearing_mean" and len(bearings) < 2:
        status = "insufficient_directions"
    elif config == "bearing_mean" and concentration < .5:
        status = "low_concentration"
    elif config == "early_centers" and not centers:
        status = "no_positive_regions"
    else:
        # IDs fix every exact score tie, with identity id0 first.
        best = min(scored, key=lambda x: (x["score"], x["id"]))
        allowed = (config == "bearing_mean" or
                   best["score"] < scored[0]["score"]-IMPROVEMENT_TOLERANCE_M)
        if allowed and best["id"] != 0:
            selected, status = best["id"], "selected"
    return selected, dict(status=status, candidates=scored,
        bearing_count=len(bearings), concentration=concentration, mean_bearing_deg=mean,
        score_units="degrees" if config == "bearing_mean" else "meters",
        original_score=scored[0]["score"], selected_score=scored[selected]["score"],
        selected_id=selected, selected_permutation=scored[selected]["permutation"])
