"""A feasible waypoint in a disk minimizing a fixed two-leg Euclidean route.

The line-segment case is analytic. Other cases use scalar numerical search and
report a convex supporting-hyperplane gap, not an exact floating-point proof.
"""
import math


def _pair(value):
    point = tuple(float(x) for x in value)
    if len(point) != 2 or not all(math.isfinite(x) for x in point):
        raise ValueError('Expected two finite coordinates')
    return point


def _project(point, center, radius):
    distance = math.dist(point, center)
    if distance <= radius:
        return point
    return tuple(center[j] + radius / distance * (point[j]-center[j]) for j in (0, 1))


def two_leg_disk_waypoint(start, successor, center, radius):
    """Return an actually feasible local candidate plus numerical gap audit.

    ``gap_m`` is f(z)-max(|p-q|, f(z)+g.(c-z)-r|g|), evaluated in binary64.
    The expression is a valid exact-arithmetic upper bound on suboptimality;
    its binary64 value is a numerical residual, not an interval certificate.
    """
    p, q, c = map(_pair, (start, successor, center))
    if isinstance(radius, bool) or not math.isfinite(radius) or radius < 0:
        raise ValueError('radius must be finite and nonnegative')
    r = float(radius)
    def cost(z):
        return math.dist(z, p)+math.dist(z, q)
    legacy = _project(p, c, r)
    direct = math.dist(p, q)
    chosen, kind = legacy, 'degenerate_disk'
    if r > 0:
        if math.dist(p, c) <= r:
            chosen, kind = p, 'start_inside'
        elif direct == 0:
            kind = 'coincident_endpoints'
        else:
            direction = tuple((q[j]-p[j])/direct for j in (0, 1))
            cp = tuple(c[j]-p[j] for j in (0, 1))
            axial = sum(cp[j]*direction[j] for j in (0, 1))
            # Cross product avoids subtracting two nearly equal squared norms.
            lateral = cp[0]*direction[1]-cp[1]*direction[0]
            height2 = r*r-lateral*lateral
            intersects = False
            if height2 >= 0:
                half = math.sqrt(height2)
                entry, last = axial-half, axial+half
                if last >= 0 and entry <= direct:
                    distance = max(0., entry)
                    if distance <= direct:
                        chosen = _project(tuple(p[j]+distance*direction[j] for j in (0, 1)), c, r)
                        kind, intersects = 'segment_first_entry', True
            if not intersects:
                a = tuple(p[j]-c[j] for j in (0, 1))
                b = tuple(q[j]-c[j] for j in (0, 1))
                angle = math.atan2(a[1], a[0])
                arc = math.atan2(a[0]*b[1]-a[1]*b[0], a[0]*b[0]+a[1]*b[1])
                def point(t):
                    return (c[0]+r*math.cos(angle+t*arc), c[1]+r*math.sin(angle+t*arc))
                # The minimizer lies in the cone generated by p-c and q-c.
                # Search its minor arc; acceptance uses an independent convex
                # gap check, so correctness does not rely on a sampled grid.
                low, high = 0., 1.
                ratio = (math.sqrt(5)-1)/2
                left, right = high-ratio*(high-low), low+ratio*(high-low)
                fl, fr = cost(point(left)), cost(point(right))
                for _ in range(88):
                    if fl <= fr:
                        high, right, fr = right, left, fl
                        left = high-ratio*(high-low)
                        fl = cost(point(left))
                    else:
                        low, left, fl = left, right, fr
                        right = low+ratio*(high-low)
                        fr = cost(point(right))
                candidates = [legacy, point(0.), point(1.), point((low+high)/2)]
                chosen = min((_project(z, c, r) for z in candidates), key=cost)
                kind = 'boundary_numerical_search'
    primal = cost(chosen)
    gradient = [0., 0.]
    for endpoint in (p, q):
        distance = math.dist(chosen, endpoint)
        if distance:
            for j in (0, 1):
                gradient[j] += (chosen[j]-endpoint[j])/distance
        # Zero is a valid subgradient of a norm at its origin.
    affine = primal+sum(gradient[j]*(c[j]-chosen[j]) for j in (0, 1))-r*math.hypot(*gradient)
    lower = max(direct, affine)
    return dict(position=chosen, kind=kind, radius_m=r,
                local_length_m=primal, legacy_local_length_m=cost(legacy),
                legacy_position=legacy, support_lower_m=lower,
                gap_m=max(0., primal-lower),
                numerical_gap_only=True, distance_to_center_m=math.dist(chosen, c))
